# Generated by Django 5.2.6 on 2026-09-22 09:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200, unique=True)),
                (
                    "code_agence",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
            ],
            options={
                "db_table": "agence",
            },
        ),
        migrations.CreateModel(
            name="PortefeuilleEntree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_client", models.CharField(max_length=30, unique=True)),
                ("nom_client", models.CharField(blank=True, max_length=200, null=True)),
                ("code_gestionnaire", models.CharField(max_length=30)),
                ("code_agence", models.CharField(max_length=30)),
                (
                    "date_edition",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "date_import",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "db_table": "portefeuille_entree",
            },
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=150, unique=True)),
                ("actif", models.BooleanField(default=False)),
                (
                    "token_activation",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "token_activation_expire",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrateur"),
                            ("superviseur", "Superviseur"),
                            ("crc", "CRC"),
                            ("acrc", "ACRC"),
                            ("client", "Client"),
                        ],
                        default="client",
                        max_length=20,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("suspendu", models.BooleanField(default=False)),
                ("date_suspension", models.DateTimeField(blank=True, null=True)),
                ("motif_suspension", models.TextField(blank=True, null=True)),
                ("tentatives_echouees", models.IntegerField(default=0)),
                ("verrouille_jusqua", models.DateTimeField(blank=True, null=True)),
                (
                    "token_reinitialisation",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "token_reinitialisation_expire",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "code_client",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                (
                    "code_gestionnaire",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                ("telephone", models.CharField(blank=True, max_length=30, null=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "crc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portefeuille",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "utilisateur",
            },
        ),
        migrations.CreateModel(
            name="AcrcCrc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acrc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "crc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "acrc_crc",
                "unique_together": {("acrc", "crc")},
            },
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="crcs_assistes",
            field=models.ManyToManyField(
                blank=True,
                related_name="acrc_assistants",
                through="apurement.AcrcCrc",
                through_fields=("acrc", "crc"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="agence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crcs",
                to="apurement.agence",
            ),
        ),
        migrations.CreateModel(
            name="Dossier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=30, unique=True)),
                (
                    "type_dossier",
                    models.CharField(
                        choices=[("voyage", "Voyage"), ("ligne", "En ligne")],
                        max_length=20,
                    ),
                ),
                ("periode", models.CharField(blank=True, max_length=7, null=True)),
                (
                    "identifiant_carte",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("montant", models.FloatField(default=0.0)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("incomplet", "Incomplet"),
                            ("en_attente", "En attente"),
                            ("en_cours", "En cours"),
                            ("valide", "Valide"),
                            ("refuse", "Refuse"),
                        ],
                        default="incomplet",
                        max_length=20,
                    ),
                ),
                ("date_debut_voyage", models.DateTimeField(blank=True, null=True)),
                ("date_fin_voyage", models.DateTimeField(blank=True, null=True)),
                ("commentaire_admin", models.TextField(blank=True, null=True)),
                ("a_ete_mis_a_jour", models.BooleanField(default=False)),
                (
                    "date_creation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "date_mise_a_jour",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_mise_en_demeure", models.DateTimeField(blank=True, null=True)),
                ("delai_prolonge_le", models.DateTimeField(blank=True, null=True)),
                ("complement_demande_le", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dossiers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pris_en_charge_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dossier",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="JournalEvenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_evenement",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("role_acteur", models.CharField(blank=True, max_length=20, null=True)),
                ("type_action", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "journal_evenement",
                "ordering": ["-date_evenement"],
            },
        ),
        migrations.CreateModel(
            name="LigneTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_operation", models.DateTimeField(blank=True, null=True)),
                ("libelle", models.CharField(max_length=300)),
                ("montant", models.FloatField()),
                ("devise", models.CharField(default="XAF", max_length=10)),
                ("montant_reel", models.FloatField(blank=True, null=True)),
                (
                    "devise_transaction",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("hors_plafond", models.BooleanField(default=False)),
                (
                    "rrn",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="apurement.dossier",
                    ),
                ),
            ],
            options={
                "db_table": "ligne_transaction",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_fichier", models.CharField(max_length=200)),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("passeport", "Passeport"),
                            ("billet_aller", "Billet aller"),
                            ("billet_retour", "Billet retour"),
                            ("visa", "Visa"),
                            ("autre_justificatif", "Autre justificatif"),
                            ("facture_proforma", "Facture proforma"),
                            ("contrat", "Contrat"),
                            ("justificatif_scolarite", "Justificatif de scolarite"),
                            ("justificatif_sante", "Justificatif medical / sante"),
                            ("justificatif_hotel", "Reservation hotel"),
                            ("justificatif", "Justificatif"),
                        ],
                        max_length=30,
                    ),
                ),
                ("chemin", models.CharField(max_length=300)),
                ("donnees_ocr", models.TextField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("valide", "Valide"),
                            ("refuse", "Refuse"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("motif_refus", models.TextField(blank=True, null=True)),
                (
                    "date_upload",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="apurement.dossier",
                    ),
                ),
                (
                    "ligne",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="justificatifs",
                        to="apurement.lignetransaction",
                    ),
                ),
            ],
            options={
                "db_table": "document",
            },
        ),
    ]
